"""Choose student-owned exact token positions from semantic text regions."""

from __future__ import annotations

from collections import defaultdict

from rlm_train.settings.token_selection import TokenScope
from rlm_train.token_selection.selection import (
    SelectedGenerationTokens,
    TokenSelection,
    TokenSelectionResult,
    selection_for_schema_v1,
)
from rlm_train.trajectory.schema import (
    AnnotatedRollout,
    ContentKind,
    DecisionRole,
    NodeRole,
    SemanticSpan,
)


def choose_tokens(
    attempt: AnnotatedRollout,
    *,
    training_method: str,
    included_text: TokenScope,
    student_id: str,
) -> TokenSelectionResult:
    """Return exact original positions without slicing them into new sequences."""
    generations_by_id = {
        generation.generation_id: generation
        for generation in attempt.annotations.generations
        if generation.policy_owner == student_id
    }
    selected_spans: list[SemanticSpan] = []
    if included_text is not TokenScope.ALL_STUDENT_TOKENS:
        for span in attempt.annotations.semantic_spans:
            if span.policy_owner != student_id or span.generation_id not in generations_by_id:
                continue
            if included_text is TokenScope.NATURAL_LANGUAGE:
                include = span.content_kind is ContentKind.NATURAL_LANGUAGE
            elif included_text is TokenScope.HELPER_QUESTIONS:
                include = span.decision_role is DecisionRole.HELPER_QUESTION
            else:
                include = span.content_kind is ContentKind.NATURAL_LANGUAGE and span.node_role in {
                    NodeRole.PLAIN_SUBCALL,
                    NodeRole.RECURSIVE_SUBCALL,
                }
            if include:
                selected_spans.append(span)

    intervals: dict[str, list[tuple[int, int, str]]] = defaultdict(list)
    if included_text is TokenScope.ALL_STUDENT_TOKENS:
        for generation in generations_by_id.values():
            if generation.token_ids:
                intervals[generation.generation_id].append(
                    (0, len(generation.token_ids), "all tokens generated by trainable student")
                )
    else:
        for span in selected_spans:
            intervals[span.generation_id].append((span.token_start, span.token_end, span.span_id))

    masks: dict[str, tuple[bool, ...]] = {}
    selected_generations: list[SelectedGenerationTokens] = []
    for generation_id, generation in generations_by_id.items():
        mask = [False] * len(generation.token_ids)
        token_sources: list[set[str]] = [set() for _ in generation.token_ids]
        for start, end, source in intervals.get(generation_id, []):
            mask[start:end] = [True] * (end - start)
            for position in range(start, end):
                token_sources[position].add(source)
        masks[generation_id] = tuple(mask)
        positions = tuple(index for index, active in enumerate(mask) if active)
        if positions:
            source_ids = tuple(
                sorted(
                    {
                        source
                        for position in positions
                        for source in token_sources[position]
                        if "/span/" in source
                    }
                )
            )
            selected_generations.append(
                SelectedGenerationTokens(
                    generation_id=generation_id,
                    positions=positions,
                    text_regions=source_ids or (f"{included_text.value} structural selection",),
                )
            )
    selection = TokenSelection(
        training_method=training_method,
        attempt_id=attempt.rollout_id,
        generations=tuple(selected_generations),
    )
    return TokenSelectionResult(
        selection=selection,
        durable=selection_for_schema_v1(
            selection,
            attempt,
            included_text=included_text,
            student_id=student_id,
        ),
        masks=masks,
    )


def choose_tokens_many(
    attempts: tuple[AnnotatedRollout, ...],
    *,
    training_method: str,
    included_text: TokenScope,
    student_id: str,
) -> dict[str, TokenSelectionResult]:
    return {
        attempt.rollout_id: choose_tokens(
            attempt,
            training_method=training_method,
            included_text=included_text,
            student_id=student_id,
        )
        for attempt in attempts
    }


__all__ = ["choose_tokens", "choose_tokens_many"]
