"""Per-objective structural token selection."""

from __future__ import annotations

from collections import defaultdict
from dataclasses import dataclass

from rlm_train.spec.objectives import TokenScope
from rlm_train.trajectory.schema import (
    AnnotatedRollout,
    ContentKind,
    DecisionRole,
    NodeRole,
    ObjectiveSelection,
    SelectedTokenRange,
    SemanticSpan,
)


@dataclass(frozen=True)
class TokenSelectionResult:
    durable: ObjectiveSelection
    masks: dict[str, tuple[bool, ...]]


def select_tokens(
    rollout: AnnotatedRollout,
    *,
    objective: str,
    token_scope: TokenScope,
    policy_owner: str,
) -> TokenSelectionResult:
    """Select only tokens owned by the configured trainable student."""
    generations = {
        generation.generation_id: generation
        for generation in rollout.annotations.generations
        if generation.policy_owner == policy_owner
    }
    selected_spans: list[SemanticSpan] = []
    if token_scope is not TokenScope.ALL_STUDENT_TOKENS:
        for span in rollout.annotations.semantic_spans:
            if span.policy_owner != policy_owner:
                continue
            if token_scope is TokenScope.NATURAL_LANGUAGE:
                include = span.content_kind is ContentKind.NATURAL_LANGUAGE
            elif token_scope is TokenScope.HELPER_QUESTIONS:
                include = span.decision_role is DecisionRole.HELPER_QUESTION
            else:
                include = span.content_kind is ContentKind.NATURAL_LANGUAGE and span.node_role in {
                    NodeRole.PLAIN_SUBCALL,
                    NodeRole.RECURSIVE_SUBCALL,
                }
            if include:
                selected_spans.append(span)

    intervals: dict[str, list[tuple[int, int, str]]] = defaultdict(list)
    if token_scope is TokenScope.ALL_STUDENT_TOKENS:
        for generation in generations.values():
            if generation.token_ids:
                intervals[generation.generation_id].append(
                    (0, len(generation.token_ids), "all tokens generated by trainable student")
                )
    else:
        for span in selected_spans:
            intervals[span.generation_id].append((span.token_start, span.token_end, span.span_id))

    masks: dict[str, tuple[bool, ...]] = {}
    ranges: list[SelectedTokenRange] = []
    for generation_id, generation in generations.items():
        mask = [False] * len(generation.token_ids)
        token_sources: list[set[str]] = [set() for _ in generation.token_ids]
        for start, end, source in intervals.get(generation_id, []):
            mask[start:end] = [True] * (end - start)
            for position in range(start, end):
                token_sources[position].add(source)
        masks[generation_id] = tuple(mask)
        start: int | None = None
        for index in range(len(mask) + 1):
            active = index < len(mask) and mask[index]
            if active and start is None:
                start = index
            elif not active and start is not None:
                ranges.append(
                    SelectedTokenRange(
                        generation_id=generation_id,
                        node_id=generation.node_id,
                        token_start=start,
                        token_end=index,
                        token_ids=generation.token_ids[start:index],
                        reason=f"{token_scope.value} structural selection",
                        source_span_ids=tuple(
                            sorted(
                                {
                                    source
                                    for position in range(start, index)
                                    for source in token_sources[position]
                                    if "/span/" in source
                                }
                            )
                        ),
                    )
                )
                start = None
    durable = ObjectiveSelection(
        objective=objective,
        token_scope=token_scope.value,
        policy_owner=policy_owner,
        ranges=tuple(ranges),
    )
    return TokenSelectionResult(durable=durable, masks=masks)


__all__ = ["TokenSelectionResult", "select_tokens"]
